config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  get 'pages/index'
  get 'pages/aboutus'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :messages
  resources :users
  resources :schedule_messages

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
end

app/models/schedule_message.rb
class ScheduleMessage < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token

  has_many :messages

  mount_uploader :avatar, AvatarUploader

  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 30 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  #return hash digest of string
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  #returns random token
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  #remember user in db for persistent session
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  #return true if given token matches digest
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  #forgets a user (so you can logout BRUH)
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  # layout :homescreen
  # private
  # def homescreen
  #   if current_user.nil?
  #     "welcome"
  #   else
  #     "application"
  #   end
  # end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  def index
    @message = Message.new
    @messages = Message.all
  end

  def create
    @message = Message.new(message_params)

    Pusher.trigger('chat', 'new_message', {
                     avatar: current_user.avatar_url(:thumb),
                     name: current_user.name,
                     message: @message.message,
                     timestamp: Time.now.strftime('%I:%M %p')
                   }, socket_id: params[:socket_id])

    respond_to :js
    @message.save unless @message.message.empty?
  end

  private

  def set_message
    @message = Message.find(params[:id])
  end

  def message_params
    params.require(:message).permit(:name, :message, :user_id, :avatar)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
  end
  def aboutus
  end
end

app/controllers/schedule_messages_controller.rb
class ScheduleMessagesController < ApplicationController
  before_action :set_schedule_message, only: [:show, :edit, :update, :destroy]

  def index
    @schedulemessage = ScheduleMessage.new
    @schedulemessages = ScheduleMessage.all
  end

  def create
    @schedulemessage = ScheduleMessage.new(schedule_message_params)

    Pusher.trigger('schedule', 'new_schedule_message', {
                     avatar: current_user.avatar_url(:thumb),
                     name: current_user.name,
                     message: @schedulemessage.message,
                     timestamp: Time.now.strftime('%I:%M %p')
                   }, socket_id: params[:socket_id])

    respond_to :js
    @schedulemessage.save
  end

  private

  def set_schedule_message
    @schedulemessage = ScheduleMessage.find(params[:id])
  end

  def schedule_message_params
    params.require(:schedule_message).permit(:name, :message, :user_id, :avatar)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_back_or user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = 'Sign up successful!!'
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def wyncode
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = 'Profile updated'
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = 'User deleted'
    redirect_to users_url
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :herefor, :githublink, :portfoliolink, :avatar, :oneliner)
  end

  # confirms logged in user present
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = 'Please log in.'
      redirect_to login_url
    end
  end

  # confirms correct user
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  # confirms admin user
  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
     layout "welcome"
  def index
    @users = User.all

  end

  def wyncode
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/schedule_messages_helper.rb
module ScheduleMessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  #logs in given user
  def log_in(user)
    session[:user_id] = user.id
  end

  #remember user in persistent session
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  #returns true if the given user is the current user
  def current_user?(user)
    user == current_user
  end

  #return user corresponding to the remember token cookie
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  #true if logged in, false if not
  def logged_in?
    !current_user.nil?
  end

  #forgest persistent session
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  #logs out current user
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  #redirects to stored location or to the default
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  #stores URL trying to be accessed but denied
  def store_location
    session[:forwarding_url] = request.url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<div id='footer-navbar'>
<div class='navbar navbar-fixed-bottom'>
  <div class="container-fluid">
    <div class='row'>
      <div class="col-xs-4 evicon">
      <li><%= link_to'<span><i class="fa fa-4x fa-users"></i></span>'.html_safe, users_path, method: "GET"%></li>
    </div>

    <div class="col-xs-4 evicon">
      <li><%= link_to'<span><i class="fa fa-4x fa-list"></i></span>'.html_safe, schedule_messages_path, method: "GET"%></li>
    </div>

    <div class="col-xs-4 evicon">
      <li><%= link_to'<span><i class="fa fa-4x fa-comments"></i></span>'.html_safe, messages_path, method: "GET"%></li>
    </div>

  </div>
</div>
</div>
</div>
<!-- <br> -->

app/views/layouts/_header.html.erb
<!-- no longer needed -->

<header>
  <div>
    <%= link_to "EVNTLR", root_path, id: "logo" %>
    <nav>
      <ul>
        <% if logged_in? %>
        <li><%= link_to "Users", users_path %></li>
        <li><%= link_to "Profile", current_user %></li>
        <li><%= link_to "Settings", edit_user_path(current_user) %></li>
        <li><%= link_to "Chat Room", messages_path %></li>
        <li>
          <%= link_to "Log out", logout_path, method: "delete" %>
        </li>
        <% else %>
        <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
<meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>
    <%= yield :title %>
  </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
        <script src="//js.pusher.com/3.0/pusher.min.js"></script>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
</head>

<body>
  <div id="container">
    <div id="canvas">
      <div id="nav">
        <!-- <h2 id="title"><i class="fa fa-sitemap"></i> MENU</h2> -->
        <ul id="toggle">
          <li>
            <div class="active border">
              <br>
              <%= link_to 'Profile', current_user, method: :get%>
              <span id="profile"><i class="fa fa-2x fa-child"></i></span>
            </div>
          </li>
          <li>
            <div>
              <%= link_to 'Get Started ', pages_aboutus_path, method: :get%>
              <span id="started"><i class="fa fa-2x fa-question"></i></span>
            </div>
          </li>
          <li>
            <div>
              <%= link_to 'Teams ', pages_index_path, method: :get%>
              <span id="about_us"><i class="fa fa-2x fa-info"></i></span>
            </div>
          </li>
          <li>
            <div>
              <%= link_to 'Log out   ', logout_path, method: :delete%>
              <span id="menu-icon"><i class="fa fa-2x fa-sign-out"></i></span>
            </div>
          </li>
        </ul>
      </div>
      <!-- nav -->
      <header id="toolbarnav">
        <div class="col-xs-4">
          <a href="#" class="toggle-nav" id="bars"><i class="fa fa-bars"></i></a>
        </div>
        <div class="col-xs-4" id="logo">
            <img src="/assets/brand-logo.png" >
        </div>
        <div class="col-xs-4 "></div>
      </header>
      <section id="content" class="clearfix">
        <!-- <%# render 'layouts/header' %> -->
        <%= yield %>
          <%= render 'layouts/footer' %>
      </section>
    </div>
    <!-- canvas -->
  </div>
  <!-- container -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
</body>

</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Welcome to Evntlr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
</head>
<body>

<%= yield %>

<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
</body>
</html>

app/views/messages/_history.html.erb
<% @messages.reverse.each do |content| %>
<% if content.message != "" %>
<li>

  <div id='user_chat'>
    <%= image_tag(content.avatar, :size => '50x50')%>
  </div>

  <p id='user_chat_name'>
    <span id='user_name'><%= content.name%></span></b><span id='created_at'><%= content.created_at.strftime("%I:%M %p") %></span><br>
       <span id='content_msg'><%= content.message %></span>

  </p>
</li>
 <% end %>

<% end %>

app/views/messages/_message.html.erb
<% if message.message != "" %>
  <li>
    <div id='user_chat'>
      <%= image_tag(current_user.avatar_url(:thumb), :size => '50x50')%>
    </div>

    <p id='user_chat_name'>
      <span id='user_name'><%= current_user.name%></span></b><span id='created_at'><%= "#{Time.now.strftime('%I:%M %p')}" %></span><br>
        <%= message.message %>

    </p>
  </li>
<% end %>

app/views/messages/create.js.erb
// clear the message box
$('#message_message').val('');

// show the message in the messages area
$('.messages').prepend('<%= escape_javascript(render @message) %>');

app/views/messages/index.html.erb
<% provide(:title, 'EVNT Buzz!') %>
<% @user = User.take %>
<div class="container-fluid allpages">
  <div class="row page-deco">
    <div class="col-xs-12 message-frame">
      <h3 class="below_nav">Give a Shout Out!</h3>
      <h4 id='chatroom_title'></h4>
      <%= form_for @message, layout: :inline, remote: true do |f| %>
      <div style="display:none">
        <%= hidden_field_tag :socket_id %>
      </div>
      <br>
      <section id='set-messages'>



        <section class="messages">

        </section>
        <%= render 'history' %>
        <br><br><br><br><br><br><br><br><br><br><br>
      </section>
    </div>
  </div>
</div>

      <div class='fixmsgsend'>
        <!-- <div class='container-fluid' style='text-align: center'> -->
          <!-- <div class='row text_group'> -->
            <div class="col-xs-9">
              <div class='whitebg'>
                <%= f.text_area :message, placeholder: "Type your messages here", :size => "75x10" %>
                <%= f.hidden_field :name, value: current_user.name %>
                <%= f.hidden_field :avatar, value: current_user.avatar_url(:thumb) %>
              </div>
            </div>
            <!-- <div class="col-xs-3"> -->

              <button type="submit" class="btn send-btn">
                <i class="fa fa-commenting"></i>
              </button>



            <% end %>
            </div>
        <!-- </div> -->
      <!-- </div> -->

app/views/pages/aboutus.html.erb
<!-- change here -->
<% provide(:title, 'EVNTLR') %>

<div class="container-fluid allpages">
  <div class="row page-deco">
    <div class="col-xs-12 message-frame">
      <p><%= image_tag 'welcome_index.png' %></p>
      <p><%= image_tag 'user_edit.png' %></p>
      <p><%= image_tag 'user_index.png' %></p>
      <p><%= image_tag 'message_index.png' %></p>
    </div>
  </div>
</div>

app/views/pages/index.html.erb
<% provide(:title, 'EVNTLR') %>

<div class="container-fluid allpages">
  <div class="row page-deco">
    <div class="col-xs-12 message-frame">
      <br>
      <a href="//www.wyncode.co"><h1>Wyncode!</h1></a>
      #LEARNTOCODE <br>
      <hr>

      <h1>Teams</h1>
      Teams are in order of pitch night.<br>
      Each team name is a link to their website! <br>
      Each team member name is a link to their EVNTLR profile!
      <hr>


      <a href="//www.evntlr.com"><h3>EVNTLR</h3></a>
      <p>EVNTLR is a platform set out to change the way we network. Network smarter with EVNTLR!</p>

      <h4>Team Members:</h4>
      <p>
        <ul style="list-style-type:disc">
          <li><%= link_to 'Jake Jacobson', '/users/38' %></li>
          <li><%= link_to 'Keith Tang', '/users/13' %></li>
          <li><%= link_to 'Paul Smailis', '/users/35' %></li>
        </ul>
      </p>
      <hr>


      <a href="//www.piktrail.com"><h3>PikTrail</h3></a>
      <p>Look up and explore a trail.</p>

      <h4>Team Members:</h4>
      <p>
        <ul style="list-style-type:disc">
          <li><%= link_to 'Dominique Miller', '/users/39' %></li>
          <li><%= link_to 'Amanda Mar Rissler', '/users/48' %></li>
          <li><%= link_to 'Jim Disser', '#' %></li>
        </ul>
      </p>
      <hr>


      <a href="http://www.tutrd.com/"><h3>Tutrd</h3></a>
      <p>On demand tutoring service.</p>

      <h4>Team Members:</h4>
      <p>
        <ul style="list-style-type:disc">
          <li><%= link_to 'Tyler Yagman', '/users/42' %></li>
          <li><%= link_to 'Todd Schwartzfarb', '/users/45' %></li>
          <li><%= link_to 'Mary Gualtieri', '/users/43' %></li>
        </ul>
      </p>
      <hr>


      <a href="http://www.theserviceworks.co/"><h3>Service Works</h3></a>
      <p>Service works connects customers seeking home improvement assistance with local service professionals.</p>

      <h4>Team Members:</h4>
      <p>
        <ul style="list-style-type:disc">
          <li><%= link_to 'Alex Miller', '/users/21' %></li>
          <li><%= link_to 'Stephanie Reyes', '/users/46' %></li>
          <li><%= link_to 'Chris Morse', '/users/44' %></li>
        </ul>
      </p>
      <hr>


      <a href="#"><h3>Hootie-Hoo!</h3></a>
      <p>Breaking the ice one hoot at a time!</p>

      <h4>Team Members:</h4>
      <p>
        <ul style="list-style-type:disc">
          <li><%= link_to 'Eric Litow', '/users/49' %></li>
          <li><%= link_to 'Beatriz Bustamante', '/users/51' %></li>
          <li><%= link_to 'Stefani Kaufman', '/users/41' %></li>
        </ul>
      </p>
      <hr>`


      <a href="https://protected-earth-6981.herokuapp.com/"><h3>GoodAdmissions</h3></a>
      <p>Dashboard to track payments, performance and availability of wyncode cohorts.</p>

      <h4>Team Members:</h4>
      <p>
        <ul style="list-style-type:disc">
          <li><%= link_to 'Diego Lugo', '/users/18' %></li>
          <li><%= link_to 'Jorge Naranjo', '/users/16' %></li>
          <li><%= link_to 'Glenn Langdon', '/users/23' %></li>
        </ul>
      </p>
      <hr>


      <a href="https://trndy.herokuapp.com/"><h3>Trndi</h3></a>
      <p>Helps you find the most popular clubs/bars with current reviews.</p>

      <h4>Team Members:</h4>
      <p>
        <ul style="list-style-type:disc">
          <li><%= link_to 'Patricio de la Guardia', '/users/36' %></li>
          <li><%= link_to 'German Nieto', '/users/19' %></li>
        </ul>
      </p>
      <br><br><br><br><br><br><br><br><br>






    </div>
  </div>
</div>

app/views/schedule_messages/_schedule_history.html.erb
<% @schedulemessages.reverse.each do |content| %>

<li>

  <div id='user_chat'>
    <%= image_tag(content.avatar, :size => '50x50')%>
  </div>

  <p id='user_chat_name'>
    <span id='user_name'><%= content.name%></span></b><span id='created_at'><%= content.created_at.strftime("%I:%M %p") %></span><br>
       <span id='content_msg'><%= content.message %></span>

  </p>
</li>


<% end %>

app/views/schedule_messages/_schedule_message.html.erb
<li>
  <div id='user_chat'>
    <%= image_tag(current_user.avatar_url(:thumb), :size => '50x50')%>
  </div>

  <p id='user_chat_name'>
    <span id='user_name'><%= current_user.name%></span></b><span id='created_at'><%= "#{Time.now.strftime('%I:%M %p')}" %></span><br>
      <%= schedule_message.message %>


  </p>
</li>

app/views/schedule_messages/create.js.erb
// clear the message box
$('#schedule_message_message').val('');

// show the message in the messages area
$('.schedule_messages').prepend('<%= escape_javascript(render @schedulemessage) %>');

app/views/schedule_messages/index.html.erb
<% provide(:title, 'Wyncode FLL CO3 Pitch Night') %>
<div class="container-fluid allpages">
  <div class="row page-deco">

    <div class="col-xs-12 message-frame">
      <h1 class="below_nav">Welcome to PITCH DAY!</h1>
      <h3 class="below_nav">SCHEDULE OF EVENTS</h3>
      <%= form_for @schedulemessage, layout: :inline, remote: true do |f| %>
        <div style="display:none">
          <%= hidden_field_tag :socket_id %>
        </div>
        <br>
        <section id='set-messages'>


          <section class="schedule_messages">


          </section>
          <%= render 'schedule_history' %>

          <br><br><br><br><br><br><br><br><br>

        </section>
        <% if current_user.admin? %>
          <div class='row text_group'>
            <div class="col-xs-9">
              <%= f.text_area :message, placeholder: "Type your messages here"%>
              <%= f.hidden_field :name, value: current_user.name %>
              <%= f.hidden_field :avatar, value: current_user.avatar_url(:thumb) %>
            </div>
            <div class="col-xs-3">
              <button type="submit" class="btn send-btn">
                <i class="fa fa-commenting"></i>
              </button>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
      <% if @user.errors.any? %>
      <div id="error_explanation">
        <div class="alert alert-danger">
          The form contains
          <%= pluralize(@user.errors.count, "error") %>.
        </div>
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
      <% end %>

app/views/users/_editform.html.erb
<%= form_for @user, :html => { :multipart => true } do |f| %>
<%= render 'shared/error_messages', object: @user %>

<%= f.text_field :name, class: 'form-control', placeholder: "Full Name" %>
<%= f.email_field :email, class: 'form-control', placeholder: "Email" %>

<%= f.password_field :password, class: 'form-control', placeholder: "Password" %>
<%= f.password_field :password_confirmation, class: 'form-control', placeholder: "Confirm Password" %>

<br>
<b>OPTIONAL INFORMATION:</b>
<br><br>

<b>Profile Picture</b>
<%= f.file_field :avatar %>
<br>
Why I'm Here:
<%= f.text_field :herefor, class: 'form-control', placeholder: "(Student, Business, Family, Friend)" %>

Github Username:
<%= f.text_field :githublink, class: 'form-control', placeholder: "(ONLY Username)" %>

Portfolio URL:
<%= f.text_field :portfoliolink, class: 'form-control', placeholder: "Portfolio Site" %>

One Liner:
<%= f.text_field :oneliner, class: 'form-control', placeholder: "(Can be a quote, phrase, etc)" %>


<%= f.submit yield(:button_text), class: "btn checkin" %>
<% end %>
<br><br><br><br>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
<%= render 'shared/error_messages', object: @user %>

<%= f.text_field :name, class: 'form-control', placeholder: "Full Name" %>

<%= f.email_field :email, class: 'form-control', placeholder: "Email" %>

<%= f.hidden_field :password, value: "password" %>

<%= f.hidden_field :password_confirmation, value: "password" %>

<br>

<%= f.submit yield(:button_text), class: "btn checkin" %>
<% end %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="container-fluid allpages">

  <div class="row">
    <div class="col-xs-12 message-frame">
      <section class="user_info">
        <br><br>
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>">
            <%= message %>
          </div>
          <% end %>

          <% if current_user == @user %>
            <%= link_to "Edit", edit_user_path, class: "btn checkin", method: :get%>
          <% end %>
        <div class='profilepic'>
          <!-- This is where profile pic will go -->
        <%= image_tag(@user.avatar_url(:profile_avatar), :size => '204x204')%>
        </div>
        <h1 id='userpage_name'>
          <%= @user.name %>
        </h1>

        <br>
        <table class='table table_bio'>
          <thead>
          <tr>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><i class="fa fa-envelope"></i></td>
            <td id="left"><b>Email:</b></td>
            <td id="right"><%= @user.email %></td>
          </tr>

          <tr>
            <td><i class="fa fa-beer"></i></td>
            <td id="left"><b>Why I'm Here:</b></td>
            <td id="right"><%= @user.herefor %></td>
          </tr>

          <tr>
            <td><i class="fa fa-github-alt"></i></td>
            <td id="left"><b>Github:</b></td>
            <td id="right"><a href="https://www.github.com/<%= @user.githublink %>">github.com/<%= @user.githublink %></a></td>
          </tr>

          <tr>
            <td><i class="fa fa-user"></i></td>
            <td id="left"><b>Portfolio:</b></td>
            <td id="right"><a href="https://<%= @user.portfoliolink %>"><%= @user.portfoliolink %></a></td>
          </tr>

          <tr>
            <td><i class="fa fa-star"></i></td>
            <td id="left"><b>One Liner:</b></td>
            <td id="right"><%= @user.oneliner %></td>
          </tr>

        </div>

      </tbody>
      </table>

      </section>
      <br><br><br><br><br><br><br><br><br><br>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<% provide(:button_text, 'Sign up') %>

<div class="container-fluid welcome-body">
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2"></div>
    <div class="home-logo">
      <img src="/assets/brand-logo.png"/>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12">
      <div class="check-in-form">
        <%= render 'users/form', :@user => User.new %>
        <% if logged_in? %>
          <%= button_to "Check In", current_user, class: "btn checkin", method: :get%>
        <% else %>
          <%= button_to "Check In", login_path, class: "btn checkin", method: :get%>
        <% end %>
        <br>
        <br>
        <br>
        <br>
        <br>
      </div>
    </div>
  </div>
</div>